'use client';

import { useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Job = { id: string; title: string; companyName: string; city: string; industry: string; salaryMinMonthly: number | null; salaryMaxMonthly: number | null; salaryMonths: number; matchScore: number; skillScore: number; hitSkills: string[]; missingSkills: string[]; sourceUrl: string | null };

export function JobPostingBrowser({ initialJobs, locale }: { initialJobs: Job[]; locale: string }) {
  const zh = locale.startsWith('zh');
  const [sort, setSort] = useState<'match' | 'salary' | 'skills'>('match');
  const [industry, setIndustry] = useState('*');
  const industries = [...new Set(initialJobs.map((job) => job.industry).filter(Boolean))].sort();
  const jobs = useMemo(() => initialJobs.filter((job) => industry === '*' || job.industry === industry).sort((a, b) => sort === 'salary'
    ? (b.salaryMaxMonthly ?? 0) - (a.salaryMaxMonthly ?? 0) : sort === 'skills' ? b.skillScore - a.skillScore : b.matchScore - a.matchScore), [initialJobs, industry, sort]);
  const salary = (job: Job) => job.salaryMinMonthly && job.salaryMaxMonthly ? `¥${Math.round(job.salaryMinMonthly / 1000)}k–${Math.round(job.salaryMaxMonthly / 1000)}k${job.salaryMonths > 12 ? ` · ${job.salaryMonths}${zh ? '薪' : ' months'}` : ''}` : (zh ? '薪资面议' : 'Salary not listed');
  return <section aria-labelledby="live-jobs-heading" className="space-y-4"><div><h2 id="live-jobs-heading" className="text-lg font-semibold">{zh ? '招聘岗位推荐' : 'Job posting recommendations'}</h2><p className="mt-1 text-sm text-muted-foreground">{zh ? '只展示已授权导入且仍在有效期内的数据；标签来自你的已知能力证据。' : 'Only licensed, non-expired imports are shown; skill labels use your evidenced profile.'}</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Tabs value={sort} onValueChange={(value) => setSort(value as typeof sort)}><TabsList><TabsTrigger value="match">{zh ? '匹配度' : 'Match'}</TabsTrigger><TabsTrigger value="salary">{zh ? '薪资' : 'Salary'}</TabsTrigger><TabsTrigger value="skills">{zh ? '技能' : 'Skills'}</TabsTrigger></TabsList></Tabs><Select value={industry} onValueChange={setIndustry}><SelectTrigger className="sm:w-56"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="*">{zh ? '全部行业' : 'All industries'}</SelectItem>{industries.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div>{jobs.length ? <div className="grid gap-4 lg:grid-cols-2">{jobs.map((job) => <Card key={job.id} className="shadow-none"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{job.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{job.companyName} · {job.city || (zh ? '地点未注明' : 'Location not listed')}</p></div><Badge>{job.matchScore}%</Badge></div></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Badge variant="secondary">{salary(job)}</Badge>{job.industry ? <Badge variant="outline">{job.industry}</Badge> : null}</div><div><p className="text-xs font-medium text-emerald-700 dark:text-emerald-300">{zh ? '已匹配技能' : 'Matched skills'}</p><div className="mt-1 flex flex-wrap gap-1">{job.hitSkills.length ? job.hitSkills.map((skill) => <Badge key={skill} variant="secondary">✓ {skill}</Badge>) : <span className="text-xs text-muted-foreground">—</span>}</div></div><div><p className="text-xs font-medium text-amber-700 dark:text-amber-300">{zh ? '待补技能' : 'Missing skills'}</p><div className="mt-1 flex flex-wrap gap-1">{job.missingSkills.map((skill) => <Badge key={skill} variant="outline">{skill}</Badge>)}</div></div>{job.sourceUrl ? <a className="inline-flex text-sm font-medium text-brand hover:underline" href={job.sourceUrl} target="_blank" rel="noreferrer">{zh ? '查看来源岗位' : 'View source posting'}</a> : null}</CardContent></Card>)}</div> : <Card className="border-dashed shadow-none"><CardContent className="p-8 text-center text-sm text-muted-foreground">{zh ? '尚未导入已授权的招聘数据；职业知识目录仍可正常使用。' : 'No licensed job dataset has been imported yet. The occupation knowledge catalog remains available.'}</CardContent></Card>}</section>;
}
